apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ .Release.Namespace }}
  name: csr-agent-clusterrole
rules:
  - apiGroups: ["security.zephyr.solo.io"]
    resources: ["virtualmeshcertificatesigningrequests", "virtualmeshcertificatesigningrequests/status"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
