changelog:
  - type: FIX
    description: Respect kubeconfig path if specified in meshctl.
    issueLink: https://github.com/solo-io/service-mesh-hub/issues/1000
  - type: FIX
    description: Respect KUBECONFIG env var for certain meshctl commands (e.g. version)
    issueLink: https://github.com/solo-io/service-mesh-hub/issues/945
