apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ .Release.Namespace }}
  name: mesh-networking-clusterrole
rules:
  - apiGroups: ["networking.smh.solo.io"]
    resources:
      - "virtualmeshes"
      - "virtualmeshes/status"
      - "trafficpolicies"
      - "trafficpolicies/status"
      - "accesscontrolpolicies"
      - "accesscontrolpolicies/status"
      - "failoverservice"
      - "failoverservice/status"
    verbs: ["*"]
  - apiGroups: ["discovery.smh.solo.io"]
    resources: ["meshes", "meshworkloads","meshworkloads/status", "meshservices","meshservices/status"]
    verbs: ["*"]
  - apiGroups: ["security.smh.solo.io"]
    resources: ["virtualmeshcertificatesigningrequests", "virtualmeshcertificatesigningrequests/status"]
    verbs: ["*"]
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices"]
    verbs: ["*"]
  - apiGroups: ["security.istio.io"]
    resources: ["authorizationpolicies"]
    verbs: ["*"]
  - apiGroups: ["linkerd.io"]
    resources: ["serviceprofiles"]
    verbs: ["*"]
  - apiGroups: ["split.smi-spec.io"]
    resources: ["trafficsplits"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "list", "watch"]
