# TODO(ilackarms): the CircleCI build is currently disabled.
# To activate it, see https://app.circleci.com/settings/project/github/solo-io/service-mesh-hub

version: 2.1
orbs:
  protobuf: izumin5210/protobuf@0.1.0
  helm: circleci/helm@1.0.0
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      # need to upgrade plan before using large executor
      # resource_class: large
    working_directory: ~/go/src/github.com/solo-io/gloo-mesh
    steps:
      - checkout
      - protobuf/install
      - helm/install-helm-client:
          version: v3.2.4
      - run:
          name: install go
          command: |
            sudo rm -rf /usr/local/go && \
            wget https://golang.org/dl/go1.14.6.linux-amd64.tar.gz && \
            tar -xvf go1.14.6.linux-amd64.tar.gz && sudo mv go /usr/local/go && \
            export GOROOT=/usr/local/go && \
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
      - run:
          name: install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: install kind
          command: |
            curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.8.1/kind-linux-amd64
            chmod +x ./kind
            sudo mv ./kind /usr/local/bin/
      - run:
          name: install deps
          command: |
            make install-go-tools
      - run:
          name: e2e istio 1.5 tests
          no_output_timeout: 30m
          command: |
            make print-version manifest-gen

            go install github.com/onsi/ginkgo/ginkgo

            curl -sSL https://github.com/istio/istio/releases/download/1.5.2/istio-1.5.2-linux.tar.gz | tar -xzf - istio-1.5.2/bin/istioctl
            export PATH=$PWD/istio-1.5.2/bin:/opt/hostedtoolcache/kubectl/1.18.0/x64:$PATH
            make run-tests TEST_PKG=test/e2e/istio RUN_E2E=1 GINKGOFLAGS=-v NO_CLEANUP=1
