{{- $image := .Values.deployment.image }}
{{- $statsConfig := coalesce .Values.deployment.stats .Values.global.stats -}}
{{- if .Values.global  }}
{{- $image = merge .Values.deployment.image .Values.global.image }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-mesh-hub
    service-mesh-hub: mesh-group
  name: mesh-group
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service-mesh-hub: mesh-group
  template:
    metadata:
      labels:
        service-mesh-hub: mesh-group
    spec:
      serviceAccountName: mesh-group
      containers:
        - image: {{ template "image" $image }}
          imagePullPolicy: {{ $image.pullPolicy }}
          name: mesh-group
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if $statsConfig.enabled }}
            - name: START_STATS_SERVER
              value: "true"
            {{- end}}
