{{- if .Values.rbac.create }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: discovery
rules:
- apiGroups: [""]
  resources: ["configmaps", "pods", "services", "secrets", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "create"]
- apiGroups: ["gloo.solo.io"]
  resources: ["settings", "upstreams"]
  verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mesh-discovery
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "secrets", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["authentication.istio.io"]
    resources: ["meshpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "create"]
  - apiGroups: ["supergloo.solo.io"]
    resources: ["*"]
    verbs: ["*"]

{{- end }}
