apiVersion: v2
description: service-mesh-hub Helm chart for Kubernetes
home: https://solo.io
name: service-mesh-hub
version: %version%
icon: ""
sources:
  - https://github.com/solo-io/mesh-projects
keywords:
  - kubernetes
  - istio
  - mesh
  - servicemesh
  - servicemeshhub
dependencies:
  - name: mesh-discovery
    version: %version%
    repository: https://storage.googleapis.com/service-mesh-hub/mesh-discovery
  - name: mesh-networking
    version: %version%
    repository: https://storage.googleapis.com/service-mesh-hub/mesh-networking
  - name: custom-resource-definitions
    version: %version%
    repository: https://storage.googleapis.com/service-mesh-hub/custom-resource-definitions
