name: pull_request

on:
  push:
    branches:
      - 'main'
  pull_request: { }

jobs:
  check-code-gen:
    name: check-code-gen
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.3
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Protoc
        uses: solo-io/setup-protoc@master
        with:
          version: '3.6.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check code gen
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          ./ci/check-code-gen.sh

  unit-tests:
    name: unit-tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.3
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Protoc
        uses: solo-io/setup-protoc@master
        with:
          version: '3.6.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Unit Tests
        run: |
          make install-go-tools run-tests

  e2e-istio:
    name: end-to-end-istio
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        istioctl-binary: [
            'https://github.com/istio/istio/releases/download/1.7.7/istio-1.7.7-linux-amd64.tar.gz',
            'https://github.com/istio/istio/releases/download/1.8.6/istio-1.8.6-linux-amd64.tar.gz',
            'https://github.com/istio/istio/releases/download/1.9.5/istio-1.9.5-linux-amd64.tar.gz',
            'https://github.com/istio/istio/releases/download/1.10.0/istio-1.10.0-linux-amd64.tar.gz'
        ]
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.3
      - uses: engineerd/setup-kind@v0.5.0
        with:
          skipClusterCreation: "true"
          version: v0.8.0
      - name: Install Protoc
        uses: solo-io/setup-protoc@master
        with:
          version: '3.6.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.0'
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Clean
        run: make clean || true
      - name: e2e Tests
        env:
          RUN_E2E: "1"
          ISTIOCTL_BINARY: ${{ matrix.istioctl-binary }}
        run: |
          make print-version

          go install github.com/onsi/ginkgo/ginkgo

          ISTIO_VERSION=istio-$(echo $ISTIOCTL_BINARY | grep -o "download/.*/" | sed 's/\bdownload\b//g' |  sed 's/[\/]//g')
          curl -sSL $ISTIOCTL_BINARY | tar -xzf - $ISTIO_VERSION/bin/istioctl
          # move istio binary to _output, which is gitignored, to avoid `-dirty` suffix when computing version in subsequent makefile invocations
          mkdir -p _output && mv $ISTIO_VERSION _output/$ISTIO_VERSION
          export PATH=$PWD/_output/$ISTIO_VERSION/bin:/opt/hostedtoolcache/kubectl/1.18.0/x64:$PATH
          istioctl version

          make run-tests TEST_PKG=test/e2e/istio RUN_E2E=1 GINKGOFLAGS=-v

  e2e-osm:
    name: end-to-end-osm
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        osm-binary: [
            'https://github.com/openservicemesh/osm/releases/download/v0.3.0/osm-v0.3.0-linux-amd64.tar.gz',
            'https://github.com/openservicemesh/osm/releases/download/v0.4.0/osm-v0.4.0-linux-amd64.tar.gz',
        ]
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.3
      - uses: engineerd/setup-kind@v0.5.0
        with:
          skipClusterCreation: "true"
          version: v0.8.0
      - name: Install Protoc
        uses: solo-io/setup-protoc@master
        with:
          version: '3.6.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.0'
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Clean
        run: make clean || true
      - name: e2e Tests
        env:
          RUN_E2E: "1"
          OSM_BINARY: ${{ matrix.osm-binary }}
          OSM_VERSION: linux-amd64/osm
        run: |
          make print-version manifest-gen

          go install github.com/onsi/ginkgo/ginkgo

          curl -sSL $OSM_BINARY | tar -xzf - $OSM_VERSION
          # move istio binary to _output, which is gitignored, to avoid `-dirty` suffix when computing version in subsequent makefile invocations
          mkdir -p _output/.bin && mv $OSM_VERSION _output/.bin
          export PATH=$PWD/_output/.bin:/opt/hostedtoolcache/kubectl/1.18.0/x64:$PATH
          osm version

          make run-tests TEST_PKG=test/e2e/osm RUN_E2E=1 GINKGOFLAGS=-v
